// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanDriverRequisitions.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace VanDriverRequisitions.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(VanDriverDbContext))]
    [Migration("20260612111735_StrengthenedAdditionalCostContraintForMileageOrJob")]
    partial class StrengthenedAdditionalCostContraintForMileageOrJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("FeRequisitionNumber")
                .StartsAt(101L);

            modelBuilder.HasSequence("PoNumber");

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.RequisitionLimitRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Fascia")
                        .HasColumnType("int");

                    b.Property<Guid?>("FeTaskTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeTaskTypeId");

                    b.HasIndex("Category", "Fascia")
                        .IsUnique()
                        .HasFilter("[FeTaskTypeId] IS NULL");

                    b.HasIndex("Category", "FeTaskTypeId", "Fascia")
                        .IsUnique()
                        .HasFilter("[FeTaskTypeId] IS NOT NULL");

                    b.ToTable("RequisitionLimitRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequisitionLimitRules_MaxQuantity_Positive", "[MaxQuantity] > 0");

                            t.HasCheckConstraint("CK_RequisitionLimitRules_MaxRate_Positive", "[MaxRate] > 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Address2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.SubmitWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedByNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OpenFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SubmitWindows", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubmitWindows_DateRange", "[OpenTo] > [OpenFrom]");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.VanDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Address2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradersName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("TradersName");

                    b.ToTable("VanDrivers", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeAdditionalCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargingOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ChargingOption");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeAdditionalCosts", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeAdditionalCosts_Miles_NonNegative", "[Miles] IS NULL OR [Miles] >= 0");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_MutuallyExclusive", "([ChargingOption] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [TotalNumber] IS NULL AND [RatePerJob] IS NULL) OR ([ChargingOption] = 1 AND [TotalNumber] IS NOT NULL AND [RatePerJob] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_RatePerJob_NonNegative", "[RatePerJob] IS NULL OR [RatePerJob] >= 0");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_RatePerMile_NonNegative", "[RatePerMile] IS NULL OR [RatePerMile] >= 0");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_TotalNumber_NonNegative", "[TotalNumber] IS NULL OR [TotalNumber] >= 0");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeGeneralTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeTaskTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaskTypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("FeTaskTypeId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeGeneralTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeGeneralTasks_RatePerJob_NonNegative", "[RatePerJob] IS NULL OR [RatePerJob] >= 0");

                            t.HasCheckConstraint("CK_FeGeneralTasks_TotalNumber_NonNegative", "[TotalNumber] >= 0");

                            t.HasCheckConstraint("CK_FeGeneralTasks_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeMileage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeMileages", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeMileages_RatePerMile_NonNegative", "[RatePerMile] IS NULL OR [RatePerMile] >= 0");

                            t.HasCheckConstraint("CK_FeMileages_TotalMiles_NonNegative", "[TotalMiles] IS NULL OR [TotalMiles] >= 0");

                            t.HasCheckConstraint("CK_FeMileages_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Reason")
                        .IsUnique();

                    b.ToTable("FeReasons", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsVatApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RequisitionDate")
                        .HasColumnType("date");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShopCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TradersName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VanDriverCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VanDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VanDriverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionNumber")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedById", "Status");

                    b.HasIndex("ShopId", "Status");

                    b.ToTable("FeRequisitions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisitionSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId", "SubmissionNumber")
                        .IsUnique();

                    b.ToTable("FeRequisitionSubmissions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTaskType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("FeTaskTypes", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShopCodeFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopCodeTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopIdFrom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopIdTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopNameFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShopNameTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("ShopIdFrom");

                    b.HasIndex("ShopIdTo");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeTransfers_RatePerJob_NonNegative", "[RatePerJob] IS NULL OR [RatePerJob] >= 0");

                            t.HasCheckConstraint("CK_FeTransfers_TotalNumber_NonNegative", "[TotalNumber] >= 0");

                            t.HasCheckConstraint("CK_FeTransfers_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.RequisitionLimitRule", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeTaskType", "FeTaskType")
                        .WithMany()
                        .HasForeignKey("FeTaskTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeTaskType");
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeAdditionalCost", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeAdditionalCosts")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeGeneralTask", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeGeneralTasks")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeGeneralTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeGeneralTaskId");

                            b1.ToTable("FeGeneralTasks");

                            b1.WithOwner()
                                .HasForeignKey("FeGeneralTaskId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeMileage", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeMileages")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeMileageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeMileageId");

                            b1.ToTable("FeMileages");

                            b1.WithOwner()
                                .HasForeignKey("FeMileageId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisitionSubmission", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("Submissions")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTransfer", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeTransfers")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeTransferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeTransferId");

                            b1.ToTable("FeTransfers");

                            b1.WithOwner()
                                .HasForeignKey("FeTransferId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", b =>
                {
                    b.Navigation("FeAdditionalCosts");

                    b.Navigation("FeGeneralTasks");

                    b.Navigation("FeMileages");

                    b.Navigation("FeTransfers");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
