// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanDriverRequisitions.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace VanDriverRequisitions.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(VanDriverDbContext))]
    partial class VanDriverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("FeRequisitionNumber");

            modelBuilder.HasSequence("PoNumber");

            modelBuilder.HasSequence("StdRequisitionNumber");

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.CostReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Reason");

                    b.HasIndex("Scope");

                    b.HasIndex("Scope", "IsActive");

                    b.ToTable("CostReasons", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.RequisitionLimitRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Fascia")
                        .HasColumnType("int");

                    b.Property<Guid?>("FeTaskTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeTaskTypeId");

                    b.HasIndex("Category", "Fascia")
                        .IsUnique()
                        .HasFilter("[FeTaskTypeId] IS NULL");

                    b.HasIndex("Category", "FeTaskTypeId", "Fascia")
                        .IsUnique()
                        .HasFilter("[FeTaskTypeId] IS NOT NULL");

                    b.ToTable("RequisitionLimitRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequisitionLimitRules_MaxQuantity_Positive", "[MaxQuantity] > 0");

                            t.HasCheckConstraint("CK_RequisitionLimitRules_MaxRate_Positive", "[MaxRate] > 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Address2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.SubmitWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedByNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OpenFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SubmitWindows", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubmitWindows_DateRange", "[OpenTo] > [OpenFrom]");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.VanDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Address2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradersName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("TradersName");

                    b.ToTable("VanDrivers", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeAdditionalCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargingOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ReasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonTextSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ChargingOption");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("ReasonCodeSnapshot");

                    b.HasIndex("ReasonId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeAdditionalCosts", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeAdditionalCosts_Miles_Positive", "[Miles] IS NULL OR [Miles] >= 1");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_MutuallyExclusive", "([ChargingOption] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [TotalNumber] IS NULL AND [RatePerJob] IS NULL) OR ([ChargingOption] = 1 AND [TotalNumber] IS NOT NULL AND [RatePerJob] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_RatePerJob_Minimum", "[RatePerJob] IS NULL OR [RatePerJob] >= 0.01");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_RatePerMile_Minimum", "[RatePerMile] IS NULL OR [RatePerMile] >= 0.01");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_TotalNumber_Positive", "[TotalNumber] IS NULL OR [TotalNumber] >= 1");

                            t.HasCheckConstraint("CK_FeAdditionalCosts_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeGeneralTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeTaskTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaskTypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("FeTaskTypeId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeGeneralTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeGeneralTasks_RatePerJob_Minimum", "[RatePerJob] IS NULL OR [RatePerJob] >= 0.01");

                            t.HasCheckConstraint("CK_FeGeneralTasks_TotalNumber_NonNegative", "[TotalNumber] >= 0");

                            t.HasCheckConstraint("CK_FeGeneralTasks_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeMileage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeMileages", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeMileages_RatePerMile_Minimum", "[RatePerMile] IS NULL OR [RatePerMile] >= 0.01");

                            t.HasCheckConstraint("CK_FeMileages_TotalMiles_NonNegative", "[TotalMiles] IS NULL OR [TotalMiles] >= 0");

                            t.HasCheckConstraint("CK_FeMileages_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsVatApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RequisitionDate")
                        .HasColumnType("date");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShopCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TradersName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VanDriverCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VanDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VanDriverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionNumber")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedById", "Status");

                    b.HasIndex("ShopId", "Status");

                    b.ToTable("FeRequisitions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisitionSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId", "SubmissionNumber")
                        .IsUnique();

                    b.ToTable("FeRequisitionSubmissions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTaskType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("FeTaskTypes", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FeRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerJob")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShopCodeFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopCodeTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopIdFrom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopIdTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopNameFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShopNameTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("WeekEndingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FeRequisitionId");

                    b.HasIndex("ShopIdFrom");

                    b.HasIndex("ShopIdTo");

                    b.HasIndex("WeekEndingDate");

                    b.ToTable("FeTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeTransfers_RatePerJob_Minimum", "[RatePerJob] IS NULL OR [RatePerJob] >= 0.01");

                            t.HasCheckConstraint("CK_FeTransfers_TotalNumber_NonNegative", "[TotalNumber] >= 0");

                            t.HasCheckConstraint("CK_FeTransfers_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdAdditionalCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FlatCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ReasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonTextSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeType");

                    b.HasIndex("Date");

                    b.HasIndex("ReasonId");

                    b.HasIndex("StdRequisitionId");

                    b.ToTable("StdAdditionalCosts", null, t =>
                        {
                            t.HasCheckConstraint("CK_StdAdditionalCosts_ChargeShape", "([ChargeType] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [FlatCharge] IS NULL) OR ([ChargeType] = 1 AND [FlatCharge] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_StdAdditionalCosts_FlatCharge_Minimum", "[FlatCharge] IS NULL OR [FlatCharge] >= 0.01");

                            t.HasCheckConstraint("CK_StdAdditionalCosts_Miles_Positive", "[Miles] IS NULL OR [Miles] >= 1");

                            t.HasCheckConstraint("CK_StdAdditionalCosts_NumberOfBags_Positive", "[NumberOfBags] >= 1");

                            t.HasCheckConstraint("CK_StdAdditionalCosts_RatePerMile_Minimum", "[RatePerMile] IS NULL OR [RatePerMile] >= 0.01");

                            t.HasCheckConstraint("CK_StdAdditionalCosts_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdCollectionChargeBanksAndBins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargeType")
                        .HasColumnType("int");

                    b.Property<string>("CollectionTypeCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CollectionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionTypeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FlatCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationPostCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeType");

                    b.HasIndex("CollectionTypeId");

                    b.HasIndex("Date");

                    b.HasIndex("LocationId");

                    b.HasIndex("StdRequisitionId");

                    b.ToTable("StdCollectionChargesBanksAndBins", null, t =>
                        {
                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_ChargeShape", "([ChargeType] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [FlatCharge] IS NULL) OR ([ChargeType] = 1 AND [FlatCharge] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_FlatCharge_NonNegative", "[FlatCharge] IS NULL OR [FlatCharge] >= 0");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_Miles_NonNegative", "[Miles] IS NULL OR [Miles] >= 0");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_NumberOfBags_NonNegative", "[NumberOfBags] IS NULL OR [NumberOfBags] >= 0");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_RatePerMile_NonNegative", "[RatePerMile] IS NULL OR [RatePerMile] >= 0");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdCollectionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("StdCollectionTypes", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdCollectionVanPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("FilledBags")
                        .HasColumnType("int");

                    b.Property<string>("PostCodeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RatePerVanPack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VanPacksOut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate");

                    b.HasIndex("PostCodeZone");

                    b.HasIndex("StdRequisitionId");

                    b.ToTable("StdCollectionVanPacks", null, t =>
                        {
                            t.HasCheckConstraint("CK_StdCollectionVanPacks_FilledBags_NotGreaterThanVanPacksOut", "[FilledBags] <= [VanPacksOut]");

                            t.HasCheckConstraint("CK_StdCollectionVanPacks_FilledBags_Positive", "[FilledBags] >= 1");

                            t.HasCheckConstraint("CK_StdCollectionVanPacks_RatePerVanPack_Minimum", "[RatePerVanPack] >= 0.01");

                            t.HasCheckConstraint("CK_StdCollectionVanPacks_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");

                            t.HasCheckConstraint("CK_StdCollectionVanPacks_VanPacksOut_Positive", "[VanPacksOut] >= 1");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CollectionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionTypeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LocationName");

                    b.HasIndex("PostCode");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopId", "CollectionTypeId", "IsActive");

                    b.HasIndex("ShopId", "CollectionTypeId", "LocationName", "PostCode")
                        .IsUnique();

                    b.ToTable("StdLocations", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdPickup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FlatCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfHouseholds")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeType");

                    b.HasIndex("Date");

                    b.HasIndex("StdRequisitionId");

                    b.ToTable("StdPickups", null, t =>
                        {
                            t.HasCheckConstraint("CK_StdPickups_ChargeShape", "([ChargeType] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [FlatCharge] IS NULL) OR ([ChargeType] = 1 AND [FlatCharge] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_StdPickups_FlatCharge_Minimum", "[FlatCharge] IS NULL OR [FlatCharge] >= 0.01");

                            t.HasCheckConstraint("CK_StdPickups_Miles_Positive", "[Miles] IS NULL OR [Miles] >= 1");

                            t.HasCheckConstraint("CK_StdPickups_NumberOfBags_Positive", "[NumberOfBags] >= 1");

                            t.HasCheckConstraint("CK_StdPickups_NumberOfHouseholds_Positive", "[NumberOfHouseholds] >= 1");

                            t.HasCheckConstraint("CK_StdPickups_RatePerMile_Minimum", "[RatePerMile] IS NULL OR [RatePerMile] >= 0.01");

                            t.HasCheckConstraint("CK_StdPickups_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsVatApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RequisitionDate")
                        .HasColumnType("date");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShopCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TradersName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VanDriverCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VanDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VanDriverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionNumber")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedById", "Status");

                    b.HasIndex("ShopId", "Status");

                    b.ToTable("StdRequisitions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdRequisitionSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmittedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("StdRequisitionId", "SubmissionNumber")
                        .IsUnique();

                    b.ToTable("StdRequisitionSubmissions", (string)null);
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChargeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FlatCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Miles")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfBoxes")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatePerMile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShopCodeFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopCodeTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopIdFrom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopIdTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShopNameFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShopNameTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StdRequisitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedByNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeType");

                    b.HasIndex("Date");

                    b.HasIndex("ShopIdFrom");

                    b.HasIndex("ShopIdTo");

                    b.HasIndex("StdRequisitionId");

                    b.ToTable("StdTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_FlatCharge_Minimum", "[FlatCharge] IS NULL OR [FlatCharge] >= 0.01");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_Miles_Positive", "[Miles] IS NULL OR [Miles] >= 1");

                            t.HasCheckConstraint("CK_StdCollectionChargesBanksAndBins_RatePerMile_Minimum", "[RatePerMile] IS NULL OR [RatePerMile] >= 0.01");

                            t.HasCheckConstraint("CK_StdTransfers_ChargeShape", "([ChargeType] = 0 AND [Miles] IS NOT NULL AND [RatePerMile] IS NOT NULL AND [FlatCharge] IS NULL) OR ([ChargeType] = 1 AND [FlatCharge] IS NOT NULL AND [Miles] IS NULL AND [RatePerMile] IS NULL)");

                            t.HasCheckConstraint("CK_StdTransfers_DifferentShops", "[ShopIdFrom] <> [ShopIdTo]");

                            t.HasCheckConstraint("CK_StdTransfers_NumberOfBags_NonNegative", "[NumberOfBags] IS NULL OR [NumberOfBags] >= 0");

                            t.HasCheckConstraint("CK_StdTransfers_NumberOfBoxes_NonNegative", "[NumberOfBoxes] IS NULL OR [NumberOfBoxes] >= 0");

                            t.HasCheckConstraint("CK_StdTransfers_TotalValue_NonNegative", "[TotalValue] IS NULL OR [TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.Common.RequisitionLimitRule", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeTaskType", "FeTaskType")
                        .WithMany()
                        .HasForeignKey("FeTaskTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeTaskType");
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeAdditionalCost", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeAdditionalCosts")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeGeneralTask", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeGeneralTasks")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeGeneralTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeGeneralTaskId");

                            b1.ToTable("FeGeneralTasks");

                            b1.WithOwner()
                                .HasForeignKey("FeGeneralTaskId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeMileage", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeMileages")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeMileageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeMileageId");

                            b1.ToTable("FeMileages");

                            b1.WithOwner()
                                .HasForeignKey("FeMileageId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisitionSubmission", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("Submissions")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeTransfer", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", null)
                        .WithMany("FeTransfers")
                        .HasForeignKey("FeRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VanDriverRequisitions.Domain.ValueObjects.WeeklyQuantities", "Week", b1 =>
                        {
                            b1.Property<Guid>("FeTransferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Friday")
                                .HasColumnType("int")
                                .HasColumnName("Fri");

                            b1.Property<int?>("Monday")
                                .HasColumnType("int")
                                .HasColumnName("Mon");

                            b1.Property<int?>("Saturday")
                                .HasColumnType("int")
                                .HasColumnName("Sat");

                            b1.Property<int?>("Sunday")
                                .HasColumnType("int")
                                .HasColumnName("Sun");

                            b1.Property<int?>("Thursday")
                                .HasColumnType("int")
                                .HasColumnName("Thu");

                            b1.Property<int?>("Tuesday")
                                .HasColumnType("int")
                                .HasColumnName("Tue");

                            b1.Property<int?>("Wednesday")
                                .HasColumnType("int")
                                .HasColumnName("Wed");

                            b1.HasKey("FeTransferId");

                            b1.ToTable("FeTransfers");

                            b1.WithOwner()
                                .HasForeignKey("FeTransferId");
                        });

                    b.Navigation("Week")
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdAdditionalCost", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("AdditionalCosts")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdCollectionChargeBanksAndBins", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdCollectionType", null)
                        .WithMany()
                        .HasForeignKey("CollectionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("CollectionChargesBanksAndBins")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdCollectionVanPack", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("CollectionVanPacks")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdLocation", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdCollectionType", "CollectionType")
                        .WithMany()
                        .HasForeignKey("CollectionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionType");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdPickup", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("Pickups")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdRequisitionSubmission", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("Submissions")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdTransfer", b =>
                {
                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.Common.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", null)
                        .WithMany("Transfers")
                        .HasForeignKey("StdRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.FE.FeRequisition", b =>
                {
                    b.Navigation("FeAdditionalCosts");

                    b.Navigation("FeGeneralTasks");

                    b.Navigation("FeMileages");

                    b.Navigation("FeTransfers");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("VanDriverRequisitions.Domain.Entities.STD.StdRequisition", b =>
                {
                    b.Navigation("AdditionalCosts");

                    b.Navigation("CollectionChargesBanksAndBins");

                    b.Navigation("CollectionVanPacks");

                    b.Navigation("Pickups");

                    b.Navigation("Submissions");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
