services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-sql

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

    mem_limit: 2g
    cpus: 1.0

    restart: unless-stopped

volumes:
  sql_data: